### ISSUE TITLE
Installation von openocean in Openhab 2

### ISSUE THREAD

**Issue by woehrer12** [fruggy83/openocean#1]
Hallo,
Ich versuche mich schon den ganzen Abend daran openocean in meiner Openhab2 installation zu integrieren. Ich habe einen Raspberry 3 mit installiertem raspbian und darauf habe ich openhab installiert.
Als erstes habe ich versucht das komplette git in /ust/share/openhab2/addons zu packen. Aber habe das Addon dann nicht gefunden.
Auch im Ordner /opt/openhab2/addons gab es kein Erfolg.
Evtl kannst du ja hier eine kurze Anleitung schreiben wie man das Addon am schnellsten in openhab2 installieren kann

**Comment by fruggy83** [comment]
Hi @woehrer12,
gute Idee. Werde mich heute Abend mal hinsetzen und eine Anleitung schreiben, Geht es dir hierbei um die eigentliche Installation des Addons oder fehlen dir noch Informationen zur Einrichtung der Things etc.?

Eventuell hilft dir aber auch schon die Diskussion [hier](https://community.openhab.org/t/new-openhab2-enocean-binding/39917) weiter.

**Comment by fruggy83** [comment]
Hi @woehrer12,

ich habe gerade ein paar Installationshinweise hinzugefügt. Kannst du mir bitte Bescheid geben, ob diese ausreichend sind oder ob ich hier noch etwas hinzufügen sollte. Vielen Dank

**Comment by leifbladt** [comment]
Hallo @fruggy83,

ich habe auf einer Test-Instanz (Ubuntu 16.04) versucht, dein Plugin in OpenHAB 2.2.0 zu installieren. Dazu habe ich die JAR-Datei unter `/usr/share/openhab2/addons` mit korrekten Rechten (analog zu der vorhandenen `openhab-addons-2.2.0.kar`) abgelegt.

Beim Installieren über die Karaf-Konsole kommt allerdings folgender Fehler:
![bildschirmfoto 2018-03-26 um 23 18 51](https://user-images.githubusercontent.com/468575/37933827-b1a54e34-314c-11e8-8226-7f362b1e8f49.png)

Trotz dieses Fehlers sehe ich in PaperUI das Binding. Kann ich irgendwie feststellen, ob das Plug-In korrekt installiert ist? Sonst probiere ich als nächstes noch, den USB-Stick an die virtuelle Maschine zu packen.

**Comment by fruggy83** [comment]
Hallo @leifbladt,

laut Screenshot läuft das Binding schon (active). Wahrscheinlich hattest du bereits die Abhängigkeit auf Transport-serial installiert, wodurch das Binding automatisch installiert werden konnte. Ich musste damals jedoch noch explizit das Binding installieren. Dürfte ich dich bitten die Installation hints anzupassen, wenn das Binding bei dir läuft?

Gruß
Daniel

**Comment by leifbladt** [comment]
Hallo @fruggy83,

danke für die Info. Ich habe die Installations-Hinweise bereits erweitert und probiere das noch auf meinem produktiven System aus. Wenn alles geklappt hat, stelle einen PR.


Gruß,
Leif

**Comment by fruggy83** [comment]
Hallo zusammen

@leifbladt 
Vielen Dank für deine Arbeit an den Installations-Hinweisen. (s. credits ;)

@woehrer12 
Ich hoffe, dass nun alles klar ist. Falls nicht, bitte melden. Ansonsten werde ich das Issue morgen schließen.

Gruß
Daniel
