### ISSUE TITLE
FUD14 mit Dimmer und Schalter ansteuern

### ISSUE THREAD

**Issue by ekrempel** [fruggy83/openocean#102]
Hallo @fruggy83,

das scheint ja hier die Austauschplattform zu sein für WeberHäuser die etwas mit openHAB umsetzen wollen. ;-)

Ich bin gerade dabei meine Automatisierung mit deiner Implementation umzusetzen und mit etwas Recherche links und rechts bin ich schon sehr weit gekommen. Jetzt bin gerade dabei die letzten Feinheiten zu klären. 

Ich habe hier FUD14 Aktoren die bereits eingelernt sind und in openHAB als Dimmer arbeiten. Was ich nicht schaffe ist sie ein/auszuschalten ohne den Dimmwert zu ändern. Wenn ich meine physikalischen Schalter nur kurz drücke, geht das Licht an/aus. Langes drücken ändert den Dimmwert. Wenn ich jetzt per openHAB das Licht ausschalte indem ich den Dimmwert auf 0 setze, muss ich den Lichtschalter lange drücken um wieder einen neuen Dimmwert zu setzen.

Ich wäre völlig zufrieden damit, zwei Things zu haben. Eine steuert an/aus und einer die Helligkeit, bekomme es aber nicht hin. Der Dimmer selbst hat als Channel nur den Dimmwert. Zusätzlich habe ich noch versucht neben dem Dimmer noch einen weiteren Schalter zu definieren. Aber darauf reagiert der Aktor nicht. 

Kennst du einen Weg, um den Dimmer an/auszuschalten ohne den Dimmwert zu ändern?

Gruß
Erik

**Comment by fruggy83** [comment]
Hi Erik @ekrempel 

ich muss gestehen, dass ich meine Dimmer über OH bisher tatsächlich nur gedimmt aber nicht ausgeschaltet habe und ich dieses Verhalten daher noch nicht beobachtet habe. Ich hätte aber gedacht, dass ich bei einem Dimmwert von 0 ein explizites "Aus" an den Aktor schicke. Ich schaue mir das noch einmal genauer an. Viele Dank auf jeden Fall schon einmal für die Hinweise.

Bezüglich Weberhaus und openHAB scheint das hier wirklich eine einigermaßen gute Austauschplattform zu sein (wenn ich mal schneller antworten würde :) Da hat der google Algorithmus gute Arbeit geleistet. 

Grüße aus dem Weberhaus
Daniel Weber

**Comment by ekrempel** [comment]
Hallo Daniel @fruggy83,

ich habe es gerade noch einmal geprüft. Du hast Recht, wenn man den Slider auf 0 setzt geht die Lampe aus und ich kann sie am physikalischen Schalter einfach wieder auf den alten Wert starten. Anscheinend hatte ich beim Testen nicht genau 0 sondern so wenig eingestellt, dass die Lampe "aus" war. Bei meinen Lampen ist alles unter ca 15% aus.

Weil eigentlich alle gefunden Anleitungen noch OH2 sind habe ich damit begonnen die gelernten Dinge etwas zu dokumentieren. Mein Ziel ist mindestens die Dimmer, Lichter, Rollläden und Heizungssteuerungen zu dokumentieren. Damit sollte ich die nächsten Tage fertig werden. Wenn du willst kannst du da gerne einen Blick drauf werfen und kommentieren. <http://www.erikkrempel.net/blog/> 

Aktuell habe ich nur noch mit der Rückmeldung der Rollläden Probleme. Wenn ich diese aus einem der Endpunkte fahren lasse sind die zurückgemeldeten Werte ok. Aber wenn ich sie z.B. auf 50 % fahre, dort anhalte und wieder starte wird mir sofort die Endposition gemeldet. Da will ich noch etwas im Log schauen ob ich finde ob der Fehler der Actuator oder das Frontend ist. Aktuell verdächte ich eher den Actuator. Hast du auch den FSB14?

Gruß Erik

**Comment by diRk262** [comment]
Hallo Erik @ekrempel,
Ich bin zwar nicht Daniel, aber evtl kann ich dir auch helfen.
Ich nutze ebenfalls das Binding mit openhab und Eltako Geräten. Klasse Sache die @fruggy83 da entwickelt hat.
Mein Ausbau geht jedoch weit über den fud, fsr und fsb „Standard“ hinaus. Aktuell habe ich knapp 90 Enocean things über 100 Enocean items mit dem Binding laufen.

Wegen deiner Rückmeldung des fsb. Eine Rückmeldung kommt bei mir sofort nach stop des Rollos und wird ebenfalls korrekt an zb HomeKit übergeben.
Gibt ein paar Dinge die zu beachten sind.. 
Stelle die Rückfallverzögerung (RV) passend am fsb ein. Also Fahrzeit messen und den nächst größeren Wert einstellen.
Stelle in openhab die Fahrzeit (shut time) des Rollos in den Thing channel Einstellungen für den rollershutter Kanal ein.
Das item welches den Rollo steuert muss als Meta data das auto-update als false hinterlegt haben.
So habe ich es gemacht, sollte bei dir dann auch klappen..

Gruß Dirk

**Comment by ekrempel** [comment]
Hallo Dirk @diRk262,

vielen Dank für deine Antwort. 90 Things sind einiges, ich hatte mit meinen knapp 50 schon irgendwann keine Lust mehr auf das Einlernen. 

Mit deinem Tipp habe ich jetzt auch gefunden, was mir noch fehlte. Die Shut time war bereits eingestellt und auch das auto-update hatte ich irgendwo als Kommentare gefunden. Nur war mir bisher nicht klar, wo ich es eintragen muss. Blöderweise hatte ich es bisher auf verschiedenste Arten beim Thing und nicht beim Item eingetragen. Jetzt aber noch einmal an die richtige Stelle und nun passt alles.

Gruß
Erik

**Comment by diRk262** [comment]
Hallo Erik @ekrempel ,
Freut mich dass jetzt alles klappt.
Das Einlernen per Lrn und teach in ist wirklich etwas nervig.
Ich habe mir daher eine Excel Tabelle erstellt in denen die hex Codes der Adressen, abhängig von den baseid‘s, berechnet werden. Diese habe ich dann einfach von Hand per pct14 in die Aktoren geschrieben. So geht die Sache eigentlich ruck zuck.

Gruß Dirk

**Comment by fruggy83** [comment]
Hallo Dirk @diRk262 
vielen lieben Dank für deine Unterstützung beim Support 👍 Es ist wirklich schön anzusehen, wie sich die openHAB Community unterstützt.

@ekrempel 
Dein Blog gefällt mir wirklich sehr, werde ich weiter beobachten. Eventuell kann man ihn ja auch im Wiki verlinken. Wenn dir aber irgendetwas an der Dokumentation zum FUD oder FSB fehlt, würde ich das Issue gerne wieder öffnen und als Reminder für die Doku verwenden, wird leider in der Todo Liste immer wieder geschoben. Du kannst aber auch selber gerne ein PR erstellen.

Den Hinweis bzgl. PCT14 und Excel Tabelle von @diRk262 kann ich nur empfehlen. Im Wiki findest du auch ein Excel Sheet, welches ich mir damals für das Teach in erstellt habe. Das zeigt dir auch gleich die Thing Definition, wenn auch in einer älteren Fassung.

**Comment by ekrempel** [comment]
Hallo Dirk @diRk262 und Daniel @fruggy83,

Die Tabelle kannte ich schon. Dank ihr hatte ich erkannt, dass die IDs Hexwerte sind und es deshalb nicht so passt wie ich vorher gedacht hatte. Ich habe sie hier zur Doku auch ausgefüllt, fand aber das Übertragen nach PCT und besonders Hexwerte per Dropdown einzutragen so fehleranfällig, dass ich es lieber per Drehschalter getan hatte. 

Dazu vielleicht noch eine Frage an Daniel: Ist es technisch zwingend, dass man die EnOceanId zum Einlernen angibt? Ich hatte zuvor einen Wibuter und der kann Actuatoren anscheinend auch ohne die ID zu kennen einlernen. 

Ich denke nicht, dass in der Doku vom EnOcean-Binding etwas fehlt. Aktuell sehe ich sie als Sammlung von den technischen Details. Ich denke wenn man dort alle Schritte dokumentiert wird es zu unübersichtlich. Wenn mir etwas auffällt ändere ich es direkt und schicke dir einen PR. 

Ich denke ich habe das Tutorial bis Ende der Woche fertig. Die FUD habe ich heute geschrieben, es fehlen noch die FSB, die Operation Panels und einmal Korrektur lesen. 

Gruß
Erik
