### ISSUE TITLE
Verbindung über FAM14

### ISSUE THREAD

**Issue by awaescher** [fruggy83/openocean#117]
Hey @fruggy83,

ich hab jetzt schon so einiges über die kabelgebundene Verwendung der FAM14 gelesen. Ich versuche zZ auch, Kommandos über einen FAM14 zu lesen und später zu senden - allerdings bekomme ich schon keine Verbindung zwischen meiner Linux-Maschine eingerichtet.

Ich weiß, dass das jetzt nicht gerade openocean-spezifisch ist ... würdest du mir dennoch vielleicht auf die Sprünge helfen, wie ich die Geräte zu verbinden habe?

Ich hatte gehofft, dass ich den FAM14 über `lsusb` und `/dev/ttyUSB*` finden und mit `cat`  und `echo` ansprechen kann. Linux und vor allem serielle Verbindungen sind jetzt nicht unbedingt mein Spezialgebiet - daher wäre ich für jede Art von Hilfe dankbar.

BA steht am FAM14 derzeit auf `2`, ich habe bereits gelesen, dass hier `4` gesetzt werden sollte. 
Leider ist das Test-Gerät nicht bei mir im Haus verbaut, daher konnte ich auch nicht so viel herumexperimentieren wie gewollt.

**Comment by binarious** [comment]
@awaescher Ich konnte mich vom Laptop aus direkt mit dem FAM14 via USB verbinden und Daten mithilfe von `screen /dev/ttyUSB0` sehen (Berechtigungsthemen beachten - da hilft Google aber). Dann in OH ein Gateway anlegen mit dem `Path` auf `/dev/ttyUSB0`. Damit die Direktververbindung vom Binding akzeptiert wird, musst du in den erweiterten Einstellungen noch `Gateway Connected Directly to RS485 BUS` anhaken. Dann klappte es bei mir.

**Comment by awaescher** [comment]
Vielen Dank für die Antwort @binarious. Zwischenzeitlich konnte ich eine Verbindung herstellen, aber es kommt leider nur Kauderwelsch im Terminal an (unleserliche Chars, leider gerade kein Screenshot zur Hand).
Ich vermute, dass die Kommandos verschlüsselt durch die Leitung gehen oder dass ich mit einer falschen Baud-Rate unterwegs bin. So tu' ich mir als Laie natürlich sehr schwer herauszufinden, welche Kommandos überhaupt zur Verfügung stehen.

**Comment by binarious** [comment]
Das ist bei mir auch so. Ich denke, die Telegramme kann man einfach nicht im Terminal ansehen, aber darüber lässt sich erkennen, ob überhaupt irgendetwas ankommt. Mit diesem Zustand konnte ich dann das Binding konfigurieren und erfolgreich verbinden.

**Comment by awaescher** [comment]
Aaaah, sehr gut zu wissen. Ich bin einfach davon ausgegangen, dass die Konfiguration noch nicht stimmt 🤦‍♂️
