### ISSUE TITLE
Required OpenHAB version

### ISSUE THREAD

**Issue by leifbladt** [fruggy83/openocean#2]
Hi,

this may sound like a stupid question, but can I Install this plugin also with the stable version 2.2 of OpenHAB? Or do I need to upgrade to nightly builds?

Thanks,
Leif

**Comment by fruggy83** [comment]
Hi @leifbladt,

I do not see any problems running this plugung with the stable version 2.2 of OpenHAB. Did you tried it? Do you have any problems?

Best regards
Daniel

**Comment by leifbladt** [comment]
Hi @fruggy83,

thanks for your reply. I wasn't sure, if it's supposed to work. So it was easier to ask, before I mess up my installation 😄 May be it's time to think about a test installation...

So, I'll give it a try!


Best regards,
Leif
