### ISSUE TITLE
Bekomme Enoceanpi nicht zum laufen

### ISSUE THREAD

**Issue by domschi** [fruggy83/openocean#27]
Hallo,

Ich bekomme einen enoceanpi nicht zum laufen. Wenn ich ihn in Openhab2 hinzufügen wird er erkannt aber mit der falschen ttyUSB0 verbindung und er ist offline. Wenn ich ihn dann auf ttyS0 umstelle geht er online, will ich dann aber ein sensor oder switch hinzufügen geht er beim scan wieder offline. 

ich hoffe ich habe mich verständlich ausgedrückt, anbei noch ein auszum aus dem log. 

Vielleicht kann mir einer von euch einen Tip geben.

Danke

21:42:16.086 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): starting rx thread... to OFFLINE (CONFIGURATION_PENDING): trying to get bridge base id...
21:42:16.106 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'openocean:serialbridge:AI05HDEQ' has been updated.
21:42:16.121 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'openocean:serialbridge:AI05HDEQ' has been updated.
21:42:16.135 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): trying to get bridge base id... to ONLINE
21:42:16.592 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'openocean:serialbridge:AI05HDEQ' has been updated.
21:42:16.657 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'openocean:serialbridge:AI05HDEQ' has been updated.
21:42:16.677 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'openocean:serialbridge:AI05HDEQ' has been updated.
21:42:16.704 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'openocean:serialbridge:AI05HDEQ' has been updated.
21:43:15.789 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea3212d:Main_Zone' has been updated.
21:43:27.495 [INFO ] [ransceiver.OpenOceanSerialTransceiver] - Transceiver shutdown
21:43:27.511 [INFO ] [ransceiver.OpenOceanSerialTransceiver] - Transceiver shutdown
21:43:27.515 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from ONLINE to OFFLINE (CONFIGURATION_PENDING): trying to connect to gateway...
21:43:27.512 [INFO ] [overy.OpenOceanDeviceDiscoveryService] - Stopping EnOcean discovery scan
21:43:27.547 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'openocean:serialbridge:AI05HDEQ' has been updated.
21:43:27.535 [INFO ] [ransceiver.OpenOceanSerialTransceiver] - OpenOceanSerialTransceiver initialized
21:43:27.574 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): trying to connect to gateway... to OFFLINE (CONFIGURATION_PENDING): opening serial port...
21:43:27.560 [INFO ] [overy.OpenOceanDeviceDiscoveryService] - Starting EnOcean discovery and accepting teach in requests
21:43:27.610 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): opening serial port... to OFFLINE (CONFIGURATION_PENDING): starting rx thread...
21:43:27.651 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): starting rx thread... to OFFLINE (CONFIGURATION_PENDING): trying to get bridge base id...
21:43:41.008 [INFO ] [smarthome.event.ItemStateChangedEvent] - ITSchrank_Gesamtverbrauch changed from 1168.65 kWh to 1168.651 kWh
21:43:41.033 [INFO ] [smarthome.event.ItemStateChangedEvent] - ITSchrank_Leistung changed from 29.460 W to 29.110 W
21:43:44.812 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'samsungtv:tv:94d34678_84f0_92c9_2ea2_9e2751666d35' changed from ONLINE to OFFLINE
21:44:15.818 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'yamahareceiver:zone:5f9ec1b3_ed59_1900_4530_00a0dea3212d:Main_Zone' has been updated.
21:44:27.561 [INFO ] [overy.OpenOceanDeviceDiscoveryService] - Stopping EnOcean discovery scan
21:44:27.646 [INFO ] [ransceiver.OpenOceanSerialTransceiver] - Transceiver shutdown
21:44:27.681 [INFO ] [ransceiver.OpenOceanSerialTransceiver] - OpenOceanSerialTransceiver initialized
21:44:27.683 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): trying to get bridge base id... to OFFLINE (CONFIGURATION_PENDING): opening serial port...
21:44:27.752 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): opening serial port... to OFFLINE (CONFIGURATION_PENDING): starting rx thread...
21:44:27.788 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:serialbridge:AI05HDEQ' changed from OFFLINE (CONFIGURATION_PENDING): starting rx thread... to OFFLINE (CONFIGURATION_PENDING): trying to get bridge base id...
21:44:30.287 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:virtualRockerSwitch:e4d07369' changed from UNINITIALIZED to INITIALIZING
21:44:30.321 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'openocean:virtualRockerSwitch:e4d07369' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)

**Comment by fruggy83** [comment]
Hi @domschi,

also das Log sieht schon merkwürdig aus. Kannst du evtl. mal versuchen, die aktuelle Version des Bindings auszuprobieren und nach dem Hinzufügen der Bridge etwas warten, bis er online ist. Laut Log versucht er nämlich die Verbindung zum USB Dongle aufzubauen UND gleichzeitig einen AutoDiscovery auszuführen. Die Erkennung des USB Dongles prüft leider nur, ob ein USB Gerät mit einem FTDI Chip vorhanden ist. Du hast vermutlich noch einen anderen USB Dongle verbaut. In diesem Fall musst du leider die Bridge manuell hinzufügen.

Gruß
Daniel

**Comment by domschi** [comment]
Hallo fruggy63,

danke für die Hilfe. Es lag an meiner Konfiguration des Raspi. Bin etwas mit den ttyXXX durcheinander gekommen. Habe auserdem noch einen auskomentierten Eintrag in der enocean.cfg gehabt. Habe dort jetzt die für mich richtige ttyS0 Schnittstelle eingetragen und jetzt funktioniert es. Habe es mit einem FT55-rw Schalter von Eltako probiert.
Jetzt habe ich nur noch ein Problem die richtige enocean ID von meinen dezentralen Dimplex Lüftern herauszufinden. Gibt es für den Raspi ein "Scan" Program mit dem der Raspi lauscht und die Infromationen ausgibt oder geht das nur mit einem USB Dongel und der DolphinView Anwendung für Windows. 
Danke für die gute Arbeit.

domschi

**Comment by fruggy83** [comment]
Hi @domschi,

du könntest dir das openhab log ansehen. Wenn du das log level des bindings auf debug stellst, werden sämtliche empfangenen Nachrichten inkl. enoceanId ausgegeben.

Gruß
Daniel

**Comment by fruggy83** [comment]
Hi @domschi,

da das eigentliche Problem gelöst ist, würde ich das Issue jetzt schließen. Falls du noch zusätzliche Infos im Log benötigst, würde ich dich bitten, ein neues Issue zu erstellen.

Danke und Gruß
Daniel
