### ISSUE TITLE
Switching state of D2_01 EEP is not correctly parsed

### ISSUE THREAD

**Issue by fruggy83** [fruggy83/openocean#31]
Switching state of D2_01 EEP is not correctly parsed. Condition checks for STATUS_SWITCHING_ON instead of STATUS_SWITCHING_OFF.

**Comment by dominikkv** [comment]
Thx, had some troubles switching on my devices, now I know why :-)
Do you mind if I create a PR in the official repo?

**Comment by fruggy83** [comment]
Hi @dominikkv, I own only smart plugs which use these EEPs. And these devices are mainly used for measurement purposes. However this weekend I installed some christmas lights, which I wanted to switch by a timer...
I already created a [PR](https://github.com/openhab/openhab2-addons/pull/4387) in the official repo. Thanks a lot for your PRs 👍

**Comment by fruggy83** [comment]
Issue solved and solution tested.
