### ISSUE TITLE
Implementation of EEP A5-07-01 EOSWA-W-EO occupancy sensors

### ISSUE THREAD

**Issue by k00ala** [fruggy83/openocean#39]
Hey @fruggy83,

your official version has a lot of nice improvements, great work.
I wanted to use the occupancy sensors with your binding. The sensor use the EEP A5-07-01.
I tried the generic approach but stuck with the MAP transformation because of the data format from the sensor. It sends additionally to the occupancy value the super-cap voltage and solar panel current which i don't need but not fixed values.
  
For example four times the data from two different sensors (Wall and Overhead mounted)
DB_3 	DB_2	DB_1	DB0
95		7D		FF		0B
9D		7D		FF		0B
96		7C		FF		09
99		7B		FF		09	 

DB_3 = Voltage Super-Cap 0-255 (% von 0-5V)
DB_2 = Solar Panel current 0-127uA (Wrong with battery)
DB_1 = 0xff occupied or 0x00 unoccupied
DB_0 = 0x09 Wall or 0x0b overhead mounted

I tried JS transformation but it didn't get triggered. And the MAP transformation fails because of dynamic values.

Do you know a way to transform such dynamic values from a generic device to string or something?

**Comment by fruggy83** [comment]
Hello @k00ala,

have a look at #35. I implemented already the A5-07 EEP family, testing is still needed. You could do me a favor if you test this branch. I will then implement a manufacturer specific profile which also provides information about the solar panel current.

Best regards
Daniel

**Comment by k00ala** [comment]
Hey @fruggy83,

yes great, it works fine, i installed the org.openhab.binding.openocean-2.5.0-SNAPSHOT.jar file manually from the branch. The Occupancy Sensor was detected automatically in Paper UI after sending a teach in telegram with a button press at the device, and the linked items: Battery, RX State and Motion Detected channels get updated after a motion is detected.

happy greetings
Stefan

**Comment by fruggy83** [comment]
PR created [4544](https://github.com/openhab/openhab2-addons/pull/4544)
