### ISSUE TITLE
Eltako Funktelegramme Stand 2012

### ISSUE THREAD

**Issue by ThorstenOest** [fruggy83/openocean#5]
Hallo, anbei die Definition der Funktelegramme für FSR12, FUD12, ...

[Eltako Funktelegramme Stand 2012.pdf](https://github.com/fruggy83/openocean/files/1883071/Eltako.Funktelegramme.Stand.2012.pdf)

**Comment by fruggy83** [comment]
Hi @ThorstenOest,

vielen Dank für die Doku. Die Doku bestätigt auch meinen Eindruck, dass die Nachrichten der 12er und 14er Baureihe identisch sind. Die 14er Reihe sendet eben nur noch zusätzliche Bestätigungsnachrichten.
Was mich jetzt aber doch sehr wundert, ist, dass du deinen FSR12 mit dem angegebenen Mapping steuern kannst. Da der FSR12 die Nachrichten auf Bit Ebene auswertet, hätten anstelle von 0000000F:on und FFFF000F:off doch eigentlich die folgenden Nachrichten **01**00000F:on und FFFF00**0E**:off verwendet werden müssen.
Du musst aber auf jeden Fall aufpassen, wenn du das dritte Bit im vierten Byte setzt. In diesem Fall wird der Schaltzustand eigentlich blockiert und kann anschließend nicht mehr von deinen Tastern geändert werden. Steht so zumindest in der Doku, habe ich aber selber noch nicht ausprobiert.

Am besten ist es wohl, wenn du einfach das A5-38 Thing verwendest und als "EEP for sending commands" das Switching Command einstellst. Als teach in müsste eigentlich auch E0400D80 funktionieren (aus der aktuellen Doku entnommen).

Gruß
Daniel

**Comment by ThorstenOest** [comment]
Ja, ich hatte mich auch gewundert, als ich jetzt wieder in das Dokument geschaut habe, dass es so funktioniert. Aber ich kann mich nicht mehr genau erinnern wie ich auf die Settings vor 5 Jahren gekommen bin. Ich meine, es gab Probleme mit dem Repeater. Vielleicht habe ich deshalb den Schaltzustand blockiert. Ich werde am Wochenende noch einmal in  mich gehen und auch A%-38 probieren.

**Comment by ThorstenOest** [comment]
Hallo @fruggy83,

vielen Dank noch einmal für das Excel-Sheet, Für meine FUD12 sollte ich es 1:1 wie für die FUD14 übernehmen können. Das hilft schon sehr. Allerdings war ich noch nicht erfolgreich mit der Definition der Parameter für das generic thing (Mapping File, ..). Dafür hast du nicht zufällig auch ein Beispiel. Das würde mir sehr helfen.

Viele Grüße,
Thorsten

**Comment by fruggy83** [comment]
Hi @ThorstenOest,

wenn du für deinen FUD12 ein A5-38 Thing verwendest brauchst du kein Mapping File. In diesem Fall sendet das EEP Profil bereits die richtigen Nachrichten. Oder brauchst du ein Mapping Beispiel für ein anderes Device?

Gruß
Daniel

**Comment by ThorstenOest** [comment]
Hallo @fruggy83,

ich benötige das Mapping für den FSR12, bei dem A5-38 Thing nicht funktioniert. 

Viele Grüße,
Thorsten

**Comment by fruggy83** [comment]
Hi @ThorstenOest,

ich habe dir im openhab forum geantwortet, da dies evtl. für den einen/anderen auch interessant sein könnte. Falls dir noch irgendwelche Infos fehlen oder du noch Fragen hast, kannst du dich jederzeit melden. Ansonsten würde ich das Issue schließen.

Gruß
Daniel

**Comment by ThorstenOest** [comment]
Ja, bitte schließen.
