### ISSUE TITLE
Add ability to validate new values in channel "totalusage"

### ISSUE THREAD

**Issue by dominikkv** [fruggy83/openocean#66]
When combining two EEPs in one thing, and the two EEPs has different precisions, there will be cases where the value will decrease, which should not be possible for this channel.
Adding a validation where decreases smaller than 1kWh are prevented will fix this. While adding this, we can also add a validation which prevents value increases greater than 10 kWh to prevent pikes from false readings.
The validation should be configurable through channel config, with the default of no validation.

**Comment by fruggy83** [comment]
Implemented and already merged in upstream.
