### ISSUE TITLE
Editing the teach in message through PaperUI doesn't work

### ISSUE THREAD

**Issue by johanneskropf** [fruggy83/openocean#67]
Hello,
I tried doing the teach in similar to other Eltako dimming actuators but I had no success. The teach in doesnt seem to work. I would be happy to supply more information if needed. I dont know if the teach in Telegram is set right. What should I put there?
Best regards Johannes

**Comment by fruggy83** [comment]
Hi Johannes,

as stated in the community, the eltako docs say that the FSUD-230 has to use a 0x02000000 teach in telegram. Please enable the debug output and watch the teach in message. Another guy told me that sometimes the teach in message does not get updated correctly. Have not found time to analyse this further.

Best reagrds
Daniel

**Comment by johanneskropf** [comment]
Irgendwie bekomme ich wenn ich versuche das Debug Log anzuschalten ein Command not found. Der Teach in geht auf jeden Fall nicht, aber das eingegebene Telegramm verschwindet auch immer wieder aus dem Channel.

**Comment by johanneskropf** [comment]
```
2019-03-11 18:01:21.001 [ome.event.ItemCommandEvent] - Item 'TeachIn' received command ON
==> /var/log/openhab2/openhab.log <==
2019-03-11 18:01:21.019 [DEBUG] [ernal.transceiver.EnOceanTransceiver] - Enqueue new send request with ESP3 type RADIO_ERP1 without callback
2019-03-11 18:01:21.026 [DEBUG] [ernal.transceiver.EnOceanTransceiver] - Sending data, type RADIO_ERP1, payload A5E0400080FFCABA810001FFFFFFFFFF00
==> /var/log/openhab2/events.log <==
2019-03-11 18:01:21.022 [nt.ItemStatePredictedEvent] - TeachIn predicted to become ON
2019-03-11 18:01:21.044 [vent.ItemStateChangedEvent] - TeachIn changed from OFF to ON
==> /var/log/openhab2/openhab.log <==
2019-03-11 18:01:21.049 [TRACE] [ernal.transceiver.EnOceanTransceiver] - Received Sync Byte
2019-03-11 18:01:21.063 [TRACE] [ernal.transceiver.EnOceanTransceiver] - >> Received header, data length 1 optional length 0 packet type 2
2019-03-11 18:01:21.069 [DEBUG] [ernal.transceiver.EnOceanTransceiver] - RESPONSE with code RET_OK payload 00 received
2019-03-11 18:01:21.074 [TRACE] [ernal.transceiver.EnOceanTransceiver] - Response without listen
```
This is the log when I switch the Teach In item, the Teach In doesn't work 😞
![50E8D2F0-59DA-4E90-95A1-234448105817](https://user-images.githubusercontent.com/46578064/54142876-ea317080-4428-11e9-9e39-1b9950067d86.jpeg)
![69A3D90C-E10B-41A3-A841-E81122E1BC76](https://user-images.githubusercontent.com/46578064/54142877-ea317080-4428-11e9-89f5-bb4854065590.jpeg)

**Comment by johanneskropf** [comment]
Die Teach in Message scheint leider nicht richtig geupdatet zu werden. Wenn ich die Seite in PaperUI neu lade erscheint das Feld immer wieder als leer.  Ich habs jetzt erstmal aufgegeben :(

**Comment by dominikkv** [comment]
Hast du das `Thing` über die *.things DSL angelegt? Wenn ja kannst du die Werte über die Oberfläche nicht ändern. Die Syntax für das File würde so aussehen:
```
Thing centralCommand 11223344 "Deckenlicht" [ enoceanId="11223344", senderIdOffset=14, sendingEEPId="A5_38_08_02", receivingEEPId="A5_38_08_02" ] {
    Channels:
        Type teachInCMD : teachInCMD [ teachInMSG="02000000" ]
}
```

**Comment by johanneskropf** [comment]
Nein, ich benutze gar keine .things files. Hab das Thing über die PaperUI erstellt.

**Comment by fruggy83** [comment]
Hi Johannes,

kannst du das Teach in bitte einmal mit einer DSL Thing definition versuchen, so wie es @dominikkv gepostet hat. Das sollte eigentlich funktionieren.

Gruß
Daniel

**Comment by johanneskropf** [comment]
Sollte ich die PTM200 oder die A5_38_08_02 als receiving Eep nehmen? Ich werds mal versuchen, hab noch nie die DSL Thing Definitionen benutzt 🙈

**Comment by johanneskropf** [comment]
So das Einlernen hat funktioniert über die DSL Thing Definition. Weil ich nicht ein einzelnes Thing File haben wollte hab ich danach ein identisches Item über die PaperUI erstellt und das im File gelöscht, das hat auch funktioniert. Also ist es wirklich ein Bug bei dem die Teach in Message bei in der PaperUI erstellten Things beim ändern nicht richtig aktualisiert wird.
Wenn die Bridge über die UI erstellt wurde ist der Syntax übrigens:
```
Thing enocean:centralCommand:11223344:55667788 (enocean:bridge:11223344) [ enoceanId="55667788", senderIdOffset=14, sendingEEPId="A5_38_08_02", receivingEEPId="A5_38_08_02" ] {
    Channels:
        Type teachInCMD : teachInCMD [ teachInMSG="02000000" ]
}
```
Danke nochmal für die Hilfe

**Comment by fruggy83** [comment]
Hi Johannes,

du hast es richtig gemacht, nimm die A5_38_08_02 als receiving Eep. Die PTM200 würde zwar auch funktionieren, dann bekommst du aber nur noch An/Aus und nicht mehr die Prozentwerte vom Dimmer. 

Ich würde immer empfehlen die DSL Thing und Item Files zu nutzen. So kannst du sehr einfach ein Backup erstellen und hast alles zentral in zwei Dateien liegen ohne, dass du dich durch mehrere Seiten in der PaperUI hangeln musst. Leider geht es aber manchmal eben nicht ohne PaperUI (UTE Teachin) und als Einstieg ist sie natürlich auch sehr hilfreich. Wenn du im Repo ganz nach unten scrollst findest du auch einige Beispiele, wie du Bridge und Things anlegen musst.

Gruß
Daniel

ps Ich würde das Issue heute Abend umbenennen und auf das Problem mit dem teachInCMD eingehen. Der Dimmer funktioniert jetzt ja.

**Comment by johanneskropf** [comment]
Ja gerne das wäre gut wenn die Issue umbenannt wird, wollte auch schon fragen ob ich dafür eine neue aufmachen soll.
Ich versuche das DSL Format so gut es geht aus mehreren Gründen zu vermeiden. Ich möchte gerne alles wenn möglich vom Ipad aus Administrieren können und möglichst einheitlich gestalten. Zusätzlich sieht es ja auch so aus würde das DSL Format irgendwann Richtung Openhab 3 obsolet werden.
Als Rules Engine hab ich sowieso Node-red über MQTT angebunden und als Backup schreibe Ich ganze Disk Images von meiner Raspberry SSD die ich im Fall einfach auf ne neue flashe.
Grüße aus Berlin
Johannes

**Comment by fruggy83** [comment]
Hi Johannes @johanneskropf ,
das Problem sollte nach dem Merge von PR [#6148](https://github.com/openhab/openhab2-addons/issues/6148) gefixt sein. Hab den Fix aber nur im offiziellen Binding implementiert. Ich schließe das Issue daher.

Gruß
Daniel

ps Euer Ausflug gestern in die "schönste Stadt Deutschlands" hat sich ja gelohnt :(

**Comment by fruggy83** [comment]
Ist jetzt auch im openocean Binding enthalten
