### ISSUE TITLE
State not updated for F6-02 - Rocker Switch

### ISSUE THREAD

**Issue by martink2** [fruggy83/openocean#7]
Hi @fruggy83,

first of all thanks for taking up the task to provide an Enocean binding for OH2.

When i add my Eltako switches as thing and bind the actor channel generalSwitchB 
to a Switch Item i can control the actor and switch the light. Unfortunately when i switch 
the actor state by other means (for example with FT55 rocker switches) the state of the 
Item is not updated in OH2. When i use the rockerswitchB channel i get a proper state 
of the Item when the switch state changes but cannot switch the state from OH2 anymore.

I also tried the A5-38 - Central command profile but with this the actor is neither switching nor 
can i see the state in OH2.

I am very grateful for any hints on how to get my switches to work.

Thanks

MArtin

**Comment by fruggy83** [comment]
Hi Martin (@martink2),

first of all I have to say that the current implementation of rocker switches is not well done. It is currently a mixture of a physical and a virtual thing. However I am working on an update for this (see #6).

As the rocker switch is currently a mixture you need to link your switch item to both channels. The rockerswitchB channel represents the physical thing part. It acts as a sensor and updates the state of your item whenever you push your physical rocker switch. 
The generalSwitchB channels is the virtual part. This channel sends a corresponding enocean message when you change the state of your item. So this part can be seen as a virtual rocker switch. 
The connection between the rockerswitchB channel and your switch item is done with a system profile. However this profile has a drawback as it updates the state of your item by sending a command and not posting a state update. Therefore your virtual rocker switch will also send an enocean message whenever you hit your physical rocker. As I said, I am currently working on this unnecessary message and a cleaner representation of rocker switches.

However this rocker switch approach should always be the last option to control you switches. It is always better to directly represent your eltako switches with an A5-38 thing in openhab. So the question is, what kind of eltako switch do you own? Is it a newer one which can even send status messages (bi directional communication)?

Best regards
Daniel

**Comment by martink2** [comment]
@fruggy83 Thanks for the quick reply. Yes i tried binding both channels simultaneously which lead to a  ping-pong effect after the first state change. I found it rather strange that the actor did not react to A5-38 telegrams. The devices are FMS61NP-230V and they do send PTM200 messages. If there is some debugging i can run to narrow things down please let me know.

**Comment by martink2** [comment]
@fruggy83 so i enabled a bit of trace debugging and can see the Actor(0185F65C) is sending the following after it is being controlled by a wall switch:

```
2018-04-13 14:08:29.691 [TRACE] [nal.transceiver.OpenOceanTransceiver] - Received Sync Byte

2018-04-13 14:08:29.792 [TRACE] [nal.transceiver.OpenOceanTransceiver] - Received header, data length 7 optional length 7 packet type 1

2018-04-13 14:08:30.100 [TRACE] [nal.transceiver.OpenOceanTransceiver] - publish event for: 0185f65c

2018-04-13 14:08:30.104 [TRACE] [nal.transceiver.OpenOceanTransceiver] - f6700185f65c3001ffffffff4f00

2018-04-13 14:08:30.108 [DEBUG] [an.handler.OpenOceanBaseThingHandler] - ESP Packet f6700185f65c30 for 0185F65C received
```

With the device configured as rocker switch i can see the state changes on the sensor channel but not on the actor channel.

When i configure it as A5-38:

![image](https://user-images.githubusercontent.com/1143193/38734023-683ff8a8-3f24-11e8-8287-30c110bdaabd.png)

the device is not responding to switching commands and when its triggered via external wall switch it is sending the above update but the state of the lightswitch channel is not updated to the new sensor state.

With my Eltako dimmers i have no problem, the are responding to A5-38 and are also updated in the ui if changed via local control or wall switch.

**Comment by fruggy83** [comment]
Hi @martink2,

I googled your FMS61NP, too. The fhem project controls this actor with the switch profile. Maybe this actor really does not support the A5-38 profile.
However I finished my work on the rocker switches yesterday. So when you take the newest version of this binding you could define your items/things in the following way:

1. As the FMS61NP sends PTM status messages you must create a Rocker Switch to react on these status msgs.
2. To control your FMS61NP (send messages to it) you must create two Virtual Rocker Switches (one switch per actor channel)
3. Define two Switch items, which represent your lights
`Switch FMS61NP_CH1 "Light1" {channel="openocean:virtualRockerSwitch:AABBCCDD:virtualRockerswitch" [profile="openocean:rockerswitch-to-on-off"], channel="openocean:rockerSwitch:XXXXXXXX:0185f65c:rockerswitchA"[profile="openocean:rockerswitch-to-on-off"]}`
`Switch FMS61NP_CH2 "Light2" {channel="openocean:virtualRockerSwitch:AABBCCEE:virtualRockerswitch" [profile="openocean:rockerswitch-to-on-off"], channel="openocean:rockerSwitch:XXXXXXXX:0185f65c:rockerswitchB"[profile="openocean:rockerswitch-to-on-off"]}`

The first channel to the virtualRockerswitch is used to control your FMS61NP. So you need one thing for each FMS61NP channel. ThingId does not matter, senderId should be determined automtically (or can be set by your if you already paired some id with this actor). The second channel is the sensing channel. It updates the state of your light item, whenever your FMS61NP sends a status message. After setting these items up, you have to pair your light items with your FMS61NP.

Hope this works for you.

Best regards
Daniel

**Comment by martink2** [comment]
Hi @fruggy83,

thanks for the great support i think i get it concept. Unfortunately i have a hard time with step 2.
When i try to add Virtual Rocker I dont get it as an option in PaperUI:

![image](https://user-images.githubusercontent.com/1143193/38757544-b776e99c-3f6d-11e8-95ad-cf3deb2744dd.png)

So tried adding it manually via config file like:
```
Thing openocean:virtualRockerSwitch:AABBCCDD "kaVsDecke" @ "" [senderIdOffset="9", sendingEEPId="F6_02_01_Virtual"]
```
Unfortunately i was not able to find documentation on the parameters i need to pass?
I always get an error like:

```
2018-04-13 22:44:41.647 [DEBUG] [an.handler.OpenOceanBaseThingHandler] - initializeThing thing openocean:virtualRockerSwitch:AABBCCDD bridge status null
2018-04-13 22:44:41.656 [hingStatusInfoChangedEvent] - 'openocean:virtualRockerSwitch:AABBCCDD' changed from INITIALIZING to OFFLINE: A bridge is required
```

Is adding a Virtual Switch via PaperUI not supported and if so could you maybe post an example of a 
config with all parameters?

Thanks

Martin

**Comment by martink2** [comment]
Hi @fruggy83,

thanks a lot for all the effort I now got the switch working as expected.
I will close the thread and will keep further discussion in the other thread.

Martin
