### ISSUE TITLE
Möglichkeitenn mit den verschiedenen Gateways (TCM 300, FAM14, FTD14, FGW14)

### ISSUE THREAD

**Issue by benderl** [fruggy83/openocean#70]
Hallo @fruggy83 ,

ich bin nun auch Besitzer eines neuen Eigenheims von WeberHaus. ;-) Da ich im Vorfeld schon Erfahrungen mit OpenHAB gesammelt habe (Homematic, Modbus etc.) war mir von Anfang an klar, dass ich die Gebäudesteuerung selber mache und habe daher nur die Busaktoren und Taster verbauen lassen. Für einen Raspberry Pi 3 habe ich mir schon einen USB Stick mit TCM300 besorgt und sehe die Funktelegramme der Taster sowie ein paar Antworten der Aktoren in OpenHAB. Ein FUD14 konnte ich auch bereits ansteuern und bekomme auch Statusmeldungen, wenn der Aktor per Taster gesteuert wird. Mit den FSB14 habe ich jedoch Probleme. Ich habe gelesen, dass die den Status nur sehr unzuverlässig in den Funk senden.

Mir stellt sich gerade die Frage, ob die Anbindung des Raspi per Funk die beste Lösung ist. Viele Leute aus dem FHEM Bereich schreiben immer von direkten USB-Verkabelungen. Welche Verbindungen werden von Deinem Binding unterstützt und was ist sinnvoll? Aktuell habe ich lediglich das FAM14 im Bus. Bekommt man mehr Infos z.B. von den FSB14, wenn man sich per USB an das FAM14 verbindet oder ein FTD14 nachgerüstet wird?

In Zukunft shließe ich nicht aus, noch ein paar Funkaktoren nachzurüsten. Mit dem USB300 kann ich die ja direkt ansteuern. Wenn jedoch per USB direkt auf den Bus verbunden wird, benötige ich dann zwingend ein FTD14, wenn ich es richtig verstanden habe?

Un noch eine Frage: demnächst wird auch meine Garage aufgestellt. Wie realisiere ich die Anbindung am Besten? Von der Garage aus wird später die Beleuchtung im Garten gesteuert. Ich habe schon zwei Cat7 Leitungen in die Garage vorgesehen. Eine für Netzwerk und die andere ist noch frei. Kann darüber eine Busankopplung realisiert werden oder denke ich zu kompliziert?

Schonmal Danke für Deine Antwort und das super Binding!

**Comment by fruggy83** [comment]
Hallo @benderl,

> ich bin nun auch Besitzer eines neuen Eigenheims von WeberHaus

Herzlichen Glückwunsch, ich hoffe, dass du/ihr genauso glücklich und zufrieden seid, wie wir in unserem Weberhaus.

> Mit den FSB14 habe ich jedoch Probleme. Ich habe gelesen, dass die den Status nur sehr unzuverlässig in den Funk senden.

Wie äußern sich denn die Probleme mit dem FSB14. Hätte eigentlich gedacht, dass ich die Positionsmeldungen der Rollos mittlerweile recht zuverlässig verarbeite. Wenn ich mir ab und zu den Status ansehe, sieht das zumindest immer gut aus. Eltako hat hier aber in der Tat eine merkwürdige Implementierung der Statusnachrichten gewählt. Anstelle einer absoluten Position melden die immer nur eine relative Laufzeit. Die Position muss ich daher immer aus der zuletzt bekannten Position und der Laufzeit berechnen. Da kann es schon mal out of sync laufen. Wenn die Rollos aber komplett hoch oder runtergefahren sind, fängt sich das wieder.

> Mir stellt sich gerade die Frage, ob die Anbindung des Raspi per Funk die beste Lösung ist.

Das Binding hier auf github unterstützt bereits eine kabelgebundene Anbindung. Dieses Feature muss ich noch in das offizielle Binding zurückmergen, wenn ich die Zeit dazu finde. Unterstützt werden dabei der FAM14 (von mir getestet) als auch der FGW. Mit dem FAM14 bekommt man über USB auch nicht mehr Infos. Vorteil ist nur, dass man über USB alles zentral im Schaltschrank unterbringen kann und sich keine Gedanken über evtl. schlechten Empfang machen muss. Weberhaus hatte bei mir aber schon eine externe Antenne zentral im Haus (in der Decke) installiert. Empfangsprobleme mit den Aktoren habe ich also keine (brauche lediglich einen Repeater für meine Außensensoren). Ein Nachteil der für dich eventuell entstehen kann ist, dass (auf jeden Fall) der FAM (evtl. auch der FGW) nur ein älteres EnOcean Protokoll unterstützt und daher mit neueren Geräten wie zB intelligenten Steckdosen mit Verbrauchsmessung nichts anfangen kann. Für diese Geräte bräuchtest du also wieder einen Funkempfänger. Ich habe mich daher gegen eine kabelgebundene Lösung entschieden. Server mit USB Empfänger steht bei mir im Büro im OG, Repeater (mit schaltbarer Steckdose) in der Empore im OG, FAM Antenne ungefähr zwischen Wohn- und Esszimmer platziert.

> Wenn jedoch per USB direkt auf den Bus verbunden wird, benötige ich dann zwingend ein FTD14, wenn ich es richtig verstanden habe?

Den FTD14 brauchst du eigentlich nur wenn du dich mit dem FAM per USB verbindest und du einen Funkaktor steuern willst, der nicht am BUS hängt (zB. smarte Steckdose). Wenn du nur Aktoren auf dem Bus (FSR, FSB, FUD etc) steuern willst, brauchst du kein FTD. Wenn du wirklich externe Aktoren über FAM => FTD steuern willst, musst du aufpassen, dass die nur ältere Telegramme (RPS oder 4BS) unterstützen, da über den Bus nur diese verschickt werden können. Wenn du Empfangsprobleme ausschließen kannst, ist die Funkverbindung also deutlich unkomplizierter und flexibler.

> demnächst wird auch meine Garage aufgestellt. Wie realisiere ich die Anbindung am Besten? Von der Garage aus wird später die Beleuchtung im Garten gesteuert.

Du kannst über das Cat7 Kabel den Bus im Schaltschrank mit einem neuen Bus in der Garage verbinden. Dazu brauchst du aber noch zwei FBA14 (hab ich auch bei mir im Schaltschrank verbaut, da ich noch ein paar weitere Aktoren nachgerüstet hatte und mir der Platz ausging ;) ) So ein "verteilter" Bus ist sicher möglich, habe auch schon mit Leuten Kontakt gehabt, die sich auf jeder Etage im Haus einen Bus aufgebaut hatten. Ich hatte zum Glück die Möglichkeit gehabt, genügend Leerrohre vom HWR nach außen legen zu können, damit ich die Gartenbeleuchtung auch im zentralen Schaltschrank unterbringen konnte. In die Garage geht nur Strom und ein Cat7 für einen Arduino mit MQTT Client, zwei Relais zum Öffnen/Schließen der Garagentore und ein paar Reedkontakte zum Überwachen. Willst du deine Tore direkt über EnOcean ansteuern?

Gruß
Daniel

**Comment by benderl** [comment]
Hallo @fruggy83,

> > Mit den FSB14 habe ich jedoch Probleme. Ich habe gelesen, dass die den Status nur sehr unzuverlässig in den Funk senden.
> 
> Wie äußern sich denn die Probleme mit dem FSB14. Hätte eigentlich gedacht, dass ich die Positionsmeldungen der Rollos mittlerweile recht zuverlässig verarbeite. Wenn ich mir ab und zu den Status ansehe, sieht das zumindest immer gut aus. Eltako hat hier aber in der Tat eine merkwürdige Implementierung der Statusnachrichten gewählt. Anstelle einer absoluten Position melden die immer nur eine relative Laufzeit. Die Position muss ich daher immer aus der zuletzt bekannten Position und der Laufzeit berechnen. Da kann es schon mal out of sync laufen. Wenn die Rollos aber komplett hoch oder runtergefahren sind, fängt sich das wieder.

Ich hatte versucht, einen FSB14 mit einem bereits angelernten Funktaster anzusteuern, um durch die Statusmeldungen die Adresse herauszubekommen. Ich bekam jedoch nur einmal sporadisch ein Funktelegramm zu sehen. Am Wochenende habe ich mir dann einen Windows-Laptop ausgeliehen, um mit dem PCT14 das FAM14 auszulesen und so an die Busadressen zu kommen. Das hat dann auch nach ein paar Startproblemen funktioniert. Alle FSB14 sind jedoch nicht wirklich gut eingestellt, wenn ich das mit meinem jetzigen Kenntnisstand vergleiche. Die Laufzeit ist an den Drehrädchen überall auf 300 eingestellt, was 5 Minuten entspricht. Das würde auch erklären, warum ich fast keine Statustelegramme sehen konnte, denn so lange habe ich nicht gewartet. Die Zeiten passe ich als erstes an, wenn ich etwas Zeit dafür finde.

Wie sollte OpenHAB in die FSB14 eingelernt werden? Als "31 Fahrkommando mit Zeitwertübergabe von GVFS"? Bei dem FUD14 hat es mit "32 Dimmwert von GVFS / Drehtaster" super funktioniert. Ansonsten habe ich aktuell noch FSR14-LED, FSR14-2x und FSR14-4x im Bus.

> > Mir stellt sich gerade die Frage, ob die Anbindung des Raspi per Funk die beste Lösung ist.
> 
> Das Binding hier auf github unterstützt bereits eine kabelgebundene Anbindung. Dieses Feature muss ich noch in das offizielle Binding zurückmergen, wenn ich die Zeit dazu finde. Unterstützt werden dabei der FAM14 (von mir getestet) als auch der FGW. Mit dem FAM14 bekommt man über USB auch nicht mehr Infos. Vorteil ist nur, dass man über USB alles zentral im Schaltschrank unterbringen kann und sich keine Gedanken über evtl. schlechten Empfang machen muss. Weberhaus hatte bei mir aber schon eine externe Antenne zentral im Haus (in der Decke) installiert. Empfangsprobleme mit den Aktoren habe ich also keine (brauche lediglich einen Repeater für meine Außensensoren). Ein Nachteil der für dich eventuell entstehen kann ist, dass (auf jeden Fall) der FAM (evtl. auch der FGW) nur ein älteres EnOcean Protokoll unterstützt und daher mit neueren Geräten wie zB intelligenten Steckdosen mit Verbrauchsmessung nichts anfangen kann. Für diese Geräte bräuchtest du also wieder einen Funkempfänger. Ich habe mich daher gegen eine kabelgebundene Lösung entschieden. Server mit USB Empfänger steht bei mir im Büro im OG, Repeater (mit schaltbarer Steckdose) in der Empore im OG, FAM Antenne ungefähr zwischen Wohn- und Esszimmer platziert.

Die Antenne des FAM ist bei mir auch zentral im Gebäude platziert. Der Raspi kommt im finalen Ausbau ca. 2m daneben in einen Schrank. Somit sollte die Funkverbindung recht stabil sein. Bis jetzt habe ich nur einen zusätzlichen Funkaktor eingeplant, der ausschließlich von OpenHAB angesteuert wird. Ein FGW oder FTD benötige ich demnach (noch) nicht.

> > demnächst wird auch meine Garage aufgestellt. Wie realisiere ich die Anbindung am Besten? Von der Garage aus wird später die Beleuchtung im Garten gesteuert.
> 
> Du kannst über das Cat7 Kabel den Bus im Schaltschrank mit einem neuen Bus in der Garage verbinden. Dazu brauchst du aber noch zwei FBA14 (hab ich auch bei mir im Schaltschrank verbaut, da ich noch ein paar weitere Aktoren nachgerüstet hatte und mir der Platz ausging ;) ) So ein "verteilter" Bus ist sicher möglich, habe auch schon mit Leuten Kontakt gehabt, die sich auf jeder Etage im Haus einen Bus aufgebaut hatten. Ich hatte zum Glück die Möglichkeit gehabt, genügend Leerrohre vom HWR nach außen legen zu können, damit ich die Gartenbeleuchtung auch im zentralen Schaltschrank unterbringen konnte. In die Garage geht nur Strom und ein Cat7 für einen Arduino mit MQTT Client, zwei Relais zum Öffnen/Schließen der Garagentore und ein paar Reedkontakte zum Überwachen. Willst du deine Tore direkt über EnOcean ansteuern?

Da bin ich noch in der Findungsphase. ;-) Es wird sicher einfacher, eine Verbindung per LAN herzustellen und andere Aktoren mit einem entsprechenden Gateway zu verbauen. Gesteuert wird später das Garagentor sowie die Außenbeleuchtung in Garten und Vorgarten. Es kann durchaus sein, dass ich dort ein paar Homematic-Wired Aktoren verbaue, da es für die ein schlankes LAN-Gateway gibt und ich schon Erfahrung damit habe.

Gruß,
Lutz

**Comment by benderl** [comment]
Noch ein Update, da ich gerade etwas experimentiert habe:

Das FAM14 steht jetzt auf BA2 und ich habe von einem FUD14 sowie FSB14 die Adressen manuell eingetragen und danach das Teach-In als PCT gemacht. Als Ergebnis konnte ich beide Aktoren steuern.

Der Dimmer liefert auch brav seinen Zustand, selbst wenn er mit einem Taster bedient wird. Der FBS14 kann zwar angesteuert werden, aber ich erhalte keine Statusmeldungen über den Stand der Rolllade. Inzwischen habe ich auch die Laufzeit eingetragen. Gemessen habe ich ca. 25 Sekunden. Das Drehrad steht jetzt auf 30 und im Thing habe ich 25 sowohl bei der Shut Time des Channels als auch beim Poll-Intervall eingetragen. macht das so Sinn?

In OpenHAB wechselt der Rollladen immer direkt zwischen 0% und 100%, wenn ich im PaperUI rauf/runter fahre. Zwischenstände gibt es nicht, selbst wenn ich die Fahrt im UI stoppe.

So langsam überlege ich, ob es nicht einfacher wäre, die Aktoren gegen Homematik auszutauschen. Die waren wesentlich gesprächiger, was den Zustand angeht und die Bedienung per Enoecean Funktaster ist ja mit OpenHAB möglich.

Gruß,
Lutz

**Comment by fruggy83** [comment]
Hi Lutz @benderl , 

wenn der Status direkt auf 0% oder 100% wechselt, hast du wahrscheinlich das autoupdate nicht auf false gesetzt. Diese Item Property definiert, ob openHab den Status direkt wechseln soll oder ob das Binding den Statuswechsel triggert. Da unsere Reihe 14 Aktoren bidirektional sind, also auch ihren Status zurückmelden, würde ich auf allen Items das autoupdate deaktivieren. Ansonsten setzt openHab den Status beim Runterfahren direkt auf 100%, beim Stopp wird die Laufzeit vom FSB gemeldet, die ich dann aber eben von 100% abziehe => Status bleibt auf 100%. Zudem solltest du bei deinem FSB Thing neben dem A5_3F_7F_EltakoFSB auch das F6_00_00 receivingEEP aktivieren, damit du die Meldungen über das Erreichen der Endpositionen ebenfalls verarbeiten kannst. 

Gruß
Daniel

**Comment by benderl** [comment]
Hallo Daniel @fruggy83 ,

danke für die Tipps. Bis jetzt habe ich versucht, alles im PaperUI zu konfigurieren. Dort wird mir jedoch kein F6_00_00 als receiving EEP angeboten. Lediglich "Eltako FSB14...", "D2_05_00" und "A5_11_03". Und eine Kombination mit A5_11_03 wird mit einem Konfigurationsfehler quittiert. Weiter ausprobieren kann ist erst am Nachmittag. Wir sind noch nicht eingezogen.

Hast Du zufällig irgendwo eine komplette Doku zum FSB14? In den Beispielen auf GitHub steht zwar das Autoupdate drin, jedoch nicht das zusätzliche EEP. Ist das alles überhaupt im PaperUI zu konfigurieren, oder muss ich eine Konfogurationsdatei anlegen?

Gruß,
Lutz

**Comment by benderl** [comment]
Ok, inzwischen wurde beim Geräte-Scan auch mal von der Adresse des FSB14 ein F6 Telegramm erkannt. Lege ich das jetzt als weiteres Thing an und verknüpfe es mit dem selben Item wie das andere Thing?

**Comment by fruggy83** [comment]
Hi Lutz @benderl,

sorry für die späte Antwort, hatte die letzten Tage noch einiges an unseren Außenanlagen zu tun. F6_00_00 ist nur der interne Name des EEP, den benötigst du, wenn du die Things über Dateien konfigurieren willst. In der GUI heißt er "PTM200 Rollershutter status". Wenn du auf der aktuellen Version bist, kannst du das einfach zusätzlich zum "Eltako FSB14/61/71" EEP auswählen. Ein zusätzliches Thing brauchst du nicht. Das EEP aktualisiert ebenfalls das rollershutter item.

>Hast Du zufällig irgendwo eine komplette Doku zum FSB14?

Gerätespezifische Doku habe ich nicht angelegt, hatte mal überlegt so etwas hier ins Wiki zu schreiben. Die Doku vernachlässige ich aber in der Tat noch zu sehr. Ich arbeite lieber an Erweiterungen... zB neue EEPs F6-05-02 😉

**Comment by benderl** [comment]
Ok, dann muss ich wohl Dein aktuelles Binding installieren. Derzeit bin ich wieder bei dem OpenHAB Release 2.4.0. Ich komme wohl am Nachmittag wieder zum Testen.

**Comment by benderl** [comment]
Jetzt funktioniert es auch mit dem FSB14! Das mit dem PTM200 muss man auch erst einmal wissen.
Ich mache mich dann mal an die anderen Aktoren.
Danke für die Unterstützung.
