### ISSUE TITLE
Smoke Detector (#71) not merged into latest 2.5.0.3 release

### ISSUE THREAD

**Issue by benderl** [fruggy83/openocean#76]
Hi Daniel,
it seems, that you mentioned #71 in the changelog of release 2.5.0.3, but forgot to merge the code from the branch. ;-) At least with openHab 2.5.0-M4 and your release 2.5.0.3 there is no thing definition for EEP F6-05-02.

Lutz

**Comment by fruggy83** [comment]
Hi Lutz,

thanks for the hint. I just fixed it. #71 will be merged into the official binding when #73 is finished.

Daniel
