### ISSUE TITLE
Gateway turns off after a few minutes

### ISSUE THREAD

**Issue by vio2000** [fruggy83/openocean#79]
After configuring the gateway, it works quite well. 
When it runs a few minutes, I get the message: 

> 'enocean:bridge:7f378767' changed from OFFLINE (CONFIGURATION_PENDING): opening serial port... to OFFLINE (CONFIGURATION_ERROR): Port already in use

and it stops working.

logfiles attached
[openhab.log](https://github.com/fruggy83/openocean/files/3996423/openhab.log)

[EventLog.log](https://github.com/fruggy83/openocean/files/3996427/EventLog.log)

**Comment by vio2000** [comment]
[openhab.log](https://github.com/fruggy83/openocean/files/4008423/openhab.log)

Added new logfile with a detailed view at the problem enocen.binding serial

**Comment by vio2000** [comment]
After doing a complete clean install of openhabian and openhab including the complete new configuration of the serial ports, it works better. 
But there is still a problem with the gateway turning off and on periodically. 
[openhab.log](https://github.com/fruggy83/openocean/files/4009783/openhab.log)
 But after a while the problem appears again.
The problem exists, no matter which type of gateway is being used. I tried both types, GPIO and USB and after a while, it happens to both types

**Comment by fruggy83** [comment]
HI @vio2000,

thanks for the log. However I cannot see why the Transceiver is periodically shutdown. Could you try to run the system without the Waschmaschine thing? After receiving an update for the Waschmaschine the Transceiver shuts down regularily. Maybe there is something wrong with the polling???
By the way I am using a similar setup. Polling the Leistung of my Waschmaschine and triggering a rule when it is near zero again. It is running without problems here.

**Comment by vio2000** [comment]
Hi @fruggy83,
happy new year 
The Waschmaschine can't be the problem, because ist a tplink thing :)
I am still facing the problem. After doing a complete new installation again, without restoring any old data, it seems to work. 
I think, I have to dig a little deeper, to find out what the problem is.
I'll give feedback, if I find the source of the problem.
If you have any other suggestions, which could help. Please don't hesitate to contact me :)
Thanks

**Comment by vio2000** [comment]
Hi @fruggy83,
I found out, why the binding didn't work any more:
It was a problem with an addon which KARAF was not able to install. This caused an error, which caused the problem with the binding.
After removing the "ACTION"-binding from the config, the system worked properly again.
Thank you for your support

**Comment by KaletoAI** [comment]
Hi @vio2000,

i have exactly the same problem after update to 2.5. Can you tell me your solution, please?
What was the "ACTION"-binding?
Also an update to 2.5.1 doesn't help.

Thanks!

**Comment by fruggy83** [comment]
HI @Kaix76,

I had a similiar problem on another system after update to the 2.5 stable release. After stopping openhab, cleaning cache (sudo openhabcli clean-cache) and restarting openhab again everything worked fine.

If this does not help, I would reopen the issue.

Best regards
Daniel

**Comment by vio2000** [comment]
Hi @Kaix76 ,
the problem was, after upgrading the openhab to 2.5, the KARAF-console wasn't able to install the ACTION Mail plugin anymore. This caused the system to stop working properly, in a special situation. 
After removing the Action-Mail in the config-file and restarting openhab, the problem turning off the gateway was gone.
best regards
markus
