### ISSUE TITLE
Eltako FTKE not working correctly

### ISSUE THREAD

**Issue by mdillmann** [fruggy83/openocean#84]
Hi,
the FTKE does not work correctly when configured as a "contact" (EEP D5-00-01) as it uses - per Eltako-Docs EEP F6-10-00.
I could make it work by setting it up as a mechanical handle (that uses EEP F6-10-00). A handle can also send a "tilted" which the FTKE can not, so this is kind of confusing for the user.

A correct solution would be to have EEP F6-10-00 also available for contact (and document it as such).
In the Eltako-docs one can see, that FTKE is indeed different from FTK(x) - so that should be fixed in the docs as well.

<img width="413" alt="grafik" src="https://user-images.githubusercontent.com/8059940/71777739-78707780-2fa4-11ea-99ab-987200c4372b.png">

The EEP of the FTKE is in fact the same as the handle (FHF), but because of misleading headline in the docs this can be missed easily.

**Comment by fruggy83** [comment]
Thanks for the hint. I will try to implement a fix this weekend. 👍

**Comment by mdillmann** [comment]
That issue has been resolved long by the latest commit. And it is working properly.
