### ISSUE TITLE
Improved support request for Omnio UPS230/10 actuator (D2-01-01)

### ISSUE THREAD

**Issue by algol-ch** [fruggy83/openocean#89]
Hello Daniel @fruggy83 

I am struggling to control my [Omnio UPS230/10 actuator](https://www.omnio.ch/fileadmin/dateien/pdf/3110000_Bd_Be_UPS230_10_V04_021.pdf) to work with OH2.5. 
By using the rotary switch (13 LRN 13 LRN) I am able to discover a teach-in telegram. I however can only receive a RPS telegram. Setting 15 LRN 12 LRD sets the actuator to send a VLD telegram with EEP D2-01-01. It seems that the binding is not able to recognise such a telegram.
Is this something that could be added?

Regards,
Arnaud

**Comment by fruggy83** [comment]
Hi Arnaud,

EEP D2-01-01 should already be supported. Could you post a debug log when you try to do the teach in?

Best regards
Daniel

**Comment by algol-ch** [comment]
Hi Daniel @fruggy83 ,

While attempting to reproduce the issue to get some logs, I solved it! Settings through rotary dials can be a little tricky.
I have [posted my step-by-step process on OpenHAB](https://community.openhab.org/t/enocean-example-needed-please/6761/4?u=algol) should anyone run into the same pain.

Cheers,

Arnaud
